### ISSUE TITLE
[CLIENT-BUG] Text goes through Hotbar 

### ISSUE THREAD

**Issue by JustPurpleN** [EvieClient/EvieClient-Releases#10]
EDIT: NOT A BUG, I DIDN'T REALISE THIS WAS NORMAL. 

**Describe the bug**
A chat message will go through the Hotbar.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Somewhere with a chat'
2. Wait for a chat to come
3. See error

**Expected behaviour**
For Chat to go over Hotbar 

**Screenshots**
Added 
![2022-02-19_22 19 54](https://user-images.githubusercontent.com/100020119/154798852-06b1f130-9f3a-4b77-90ab-093954d24528.png)

**Desktop:**
- OS: Windows 11
- Computer Hardware Intel(R) Core(TM) i7-10510U CPU @ 1.80Ghz, 8.0GBRam, SSD, Intel(R) UHD Graphics
- Version Hash Evie Client Private Beta (There was no Hash, but the version is after aeecc04)

**Comment by tristancamejo** [comment]
That's part of vanilla but I can make it a feature to put it higher.
