### ISSUE TITLE
[CLIENT-BUG] Mod Menu too big 

### ISSUE THREAD

**Issue by JustPurpleN** [EvieClient/EvieClient-Releases#12]
**Describe the bug**
The mod menu in EvieClient is too big. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'EvieClient'
2. Click on 'Right shift'
3. See error (I think you might need a specific resolution) 

**Expected behaviour**
For the mod menu to be a good size.

**Screenshots**
![Screenshot (76)](https://user-images.githubusercontent.com/100020119/155064823-73bb62d3-36f1-4e5c-8dd4-576e8a211885.png)

**Desktop:**
- OS: Windows 11
- Computer Hardware: Intel(R) Core(TM) i7-10510U CPU @ 1.80Ghz, 8.0GBRam, SSD, Intel(R) UHD Graphics
- Version Hash: Evie Client Private Beta (7eea2b6)

**Comment by JustPurpleN** [comment]
Also, If I go to a smaller GUI Scale it looks like this: 
![Screenshot (77)](https://user-images.githubusercontent.com/100020119/155065574-7216a0e3-6585-4034-94f0-6ad4286b32be.png)

**Comment by tristancamejo** [comment]
It's not even close to done, it was just pushed to prod to make that empty menu not empty.

**Comment by JustPurpleN** [comment]
> It's not even close to done, it was just pushed to prod to make that empty menu not empty.

Ah ok,
