### ISSUE TITLE
[CLIENT-BUG] Full screen Main-Menu scaling glitch

### ISSUE THREAD

**Issue by huntriscool** [EvieClient/EvieClient-Releases#2]
**Describe the bug**
when you full screen with f11 the screen glicthes

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/99586769/154794077-8aef7c07-76fb-40a5-a482-a38226081fab.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS, etc] windows
 - Computer Hardware [e.g. CPU, GPU, RAM, the more we know the better] cpu: 5600x, gpu: 980ti, ram: 16gb
 - Version Hash (located at the bottom right of the main menu in the client)

**Additional context**

**Comment by tristancamejo** [comment]
For the future please don't include `Name your bug here...`

Also, you forgot the instructions...
![image](https://user-images.githubusercontent.com/69066026/154794219-1226f5ba-bcb4-4e92-9ba2-eb2dc4f77185.png)

But for you first bug good job!

**Comment by tristancamejo** [comment]
I'll look into it 👍

**Comment by tristancamejo** [comment]
![ZW7cB6MNmT](https://user-images.githubusercontent.com/69066026/154797382-e420f69e-c1f4-46d5-b5dd-2d3cd8ad8d79.gif)

Redesigning the whole main menu, ignore the buttons for the time being.

**Comment by tristancamejo** [comment]
![image](https://user-images.githubusercontent.com/69066026/154798630-b82b015f-5ad0-4cd2-87b1-0c702e3f591e.png)
Fixed it! The commit hash is gone in that build, but it's back.
