### ISSUE TITLE
[LAUNCHER-BUG] Launcher Scaling

### ISSUE THREAD

**Issue by toasterw** [EvieClient/EvieClient-Releases#3]
**Describe the bug**
Launcher contents scale poorly at 1440p, and the window itself scales poorly at 1440p with 200% scaling, which is required for an apple laptop with a retina display using windows

**To Reproduce**
1. Open the client on a resolution above 1080p
2. observe.

**Expected behavior**
The client to scale properly

**Screenshots**
![image](https://user-images.githubusercontent.com/71234319/154794211-b776ffb7-b47a-490b-a4ac-239b8d80f9f4.png)
![image](https://user-images.githubusercontent.com/71234319/154794221-8c808029-d46a-4150-99eb-198560c2716c.png)
(In the second screenshot the window takes up the whole screen and still overlaps)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Hardware: balls
 - Version 1.1.0

**Additional context**
beans

**Comment by toasterw** [comment]
Scaling works fine upon actually signing in

**Comment by tristancamejo** [comment]
Doesn't seem like a bug or a real problem.
