### ISSUE TITLE
[CLIENT-BUG] Mod menu crashes game

### ISSUE THREAD

**Issue by toasterw** [EvieClient/EvieClient-Releases#5]
**Describe the bug**
When I press right shift, the common hotkey to open a modification menu on most modded clients, my game instantly closes, without even hanging

**To Reproduce**
1. Join a server or singleplayer world
2. Press right shift

**Expected behavior**
Either nothing, or a menu to open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Computer Hardware: i5-8210Y, 8GB 2133 MHz SODIMM (never heard of that taking place of the ddr specification on a consumer device in my life wtf), Intel UHD Graphics 617
 - Version Hash: 4af4339

**Additional context**

**Comment by tristancamejo** [comment]
Does the game just close? Or does something else happen before it closes?
