### ISSUE TITLE
[CLIENT-BUG] If you Click L in chat it will still Enable/Disable Old Animations

### ISSUE THREAD

**Issue by JustPurpleN** [EvieClient/EvieClient-Releases#6]
If you Click L in chat it will still Enable/Disable Old Animations

**To Reproduce**
1. Go to 'chat'
2. Click on 'L'

**Expected behaviour**
Enabling/Disabling old animations not to happen

**Desktop**
- OS: Windows 11
- Computer Hardware Intel(R) Core(TM) i7-10510U CPU @ 1.80Ghz, 8.0GBRam, SSD, Intel(R) UHD Graphics
- Version Hash EvieClient Private Beta (4af4339)

**Comment by toasterw** [comment]
I think this is an intentional feature, it's meant to be a keybind to toggle the mod, however the mod listens for the keybind inside any menus, causing issues when typing things in chat or the creative search menu

**Comment by tristancamejo** [comment]
This is an intentional feature, it's so we are able to toggle it while the "mod config menu" doesn't exist.

**Comment by JustPurpleN** [comment]
> This is an intentional feature, it's so we are able to toggle it while the "mod config menu" doesn't exist.

Ok, thank you!
