### ISSUE TITLE
[CLIENT-BUG] Display Mods don't save position after relog 

### ISSUE THREAD

**Issue by JustPurpleN** [EvieClient/EvieClient-Releases#9]
**Describe the bug**
The display mods don't save position if I relog into EvieClient

**To Reproduce**
Steps to reproduce the behaviour:
1. Change position of a Mod
2. Relog into EvieClient 
3. Display Mods will be reset 

**Expected behaviour**
The Display Mods not to be moved

**Desktop:**
- OS: Windows 11
- Computer Hardware Intel(R) Core(TM) i7-10510U CPU @ 1.80Ghz, 8.0GBRam, SSD, Intel(R) UHD Graphics
- Version Hash Evie Client Private Beta (aeecc04)

**Comment by tristancamejo** [comment]
Hasn't been implemented yet, it will be when I add the Evie Config menu.

**Comment by JustPurpleN** [comment]
> Hasn't been implemented yet, it will be when I add the Evie Config menu.

Ok, thank you!
